openapi: 3.0.0
info:
  version: '1.0'
  title: EA Koppeling Notifications
tags:
  - name: Notifications
    description: >-
      API waar EA notificaties over wijzigingen naar toe stuurt, de
      implementatie van dit endpoint zit dus niet in EA
paths:
  /notifications:
    post:
      tags:
        - Notifications
      security:
        - oauth2_client_credentials:
            - write:notitications
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    oauth2_client_credentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            write:notitications: Write access Notifications
  schemas:
    Notification:
      type: object
      required:
        - event
        - objectReference
      properties:
        event:
          type: string
          enum:
            - NEW
            - UPDATE
            - DELETE
        objectReference:
          $ref: '#/components/schemas/Reference'
    Reference:
      type: object
      required:
        - externalId
        - type
      properties:
        externalId:
          type: string
        displayName:
          type: string
        type:
          type: string
        href:
          type: string
